name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ... other steps ...

      - run: bash start.sh
      #      ^
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
