name: Strapi Host
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clonar Repo
      run: echo Clonado
    - name: Actualizar Node
      run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
           nvm install 20 | bash
           node -v
           npm -v 
    - name: Descargar y logear playit para subir la Web
      run: bash bash.sh
           echo Terminado
    - name: Sshx
      run: curl -sSf https://sshx.io/get | sh -s run